# Gitlab CI yml file

# This is the major part of the code which explains the stages present in our pipeline.
# In a django application we have various stages which include testing, packing the code,
# performing migrations, collecting static files and running the application.
# The various stages are broadly classified into 3 main categories:

# 1. Test       2. Release      3. Deploy

stages:
- test
- release
# - deploy

# Stage I
# Testing Phase:
# This is where the main code is tested.
# Other options like code coverage, etc are also written in this phase
.test:
  stage: test
  # This repo includes python3, pip3
  image: python:3-alpine
  before_script:
    # Installing requirements
    - apk add --no-cache git
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
  
unit_test:
  extends: .test
  script:
    # Command to test our application
    - coverage run --source='.' --omit=*/tests.py,*/migrations/*,*/urls.py,*/settings.py,*/wsgi.py,manage.py manage.py test
    - coverage report
    - coveralls

codestyle:
  extends: .test
  script:
    - pycodestyle .

# Stage II
# Release Phase
# In this phase, we package our code using docker
.release:
  stage: release
  image: docker:latest
  services:
    - docker:dind
  script:
    # Build our image using docker
    - docker build . -t cjjcastro/hubcare-api:$DOCKERTAG

    # Configure container registry to push using docker
    - docker login -p $DOCKERPASSWORD -u $DOCKERLOGIN

    # Push the image using docker
    - docker push cjjcastro/hubcare-api:$DOCKERTAG

    # The tag, only master indicates that whenever code is pushed to master branch,
    # only then run the pipeline

release_production:
  extends: .release
  environment: production
  only: 
    - master

release_development:
  extends: .release
  environment: development
  only: 
    - devel
