# Generated by Django 2.1.7 on 2019-04-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpWanted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('repo', models.CharField(max_length=100)),
                ('total_issues', models.IntegerField(default=0)),
                ('help_wanted_issues', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(default=None)),
            ],
        ),
    ]
