# Generated by Django 2.1.7 on 2019-04-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DifferentsAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30)),
                ('repo', models.CharField(max_length=30)),
                ('commits', models.CharField(max_length=150)),
                ('date', models.DateField(max_length=150)),
            ],
        ),
    ]
