URL_COMMMUNITY = 'http://localhost:8002/'
HEIGHT_README_SUPPORT = 3
HEIGHT_ISSUE_TEMPLATE_SUPPORT = 2
HEIGHT_LICENSE_SUPPORT = 3
HEIGHT_DESCRIPTION_SUPPORT = 1
HEIGHT_CODE_OF_CONDUCT_SUPPORT = 1
HEIGHT_RELEASE_NOTE_SUPPORT = 3