URL_COMMIT = 'http://localhost:8001/'
URL_COMMUNITY = 'http://localhost:8002/'
URL_ISSUES = 'http://localhost:8003/'
URL_PR = 'http://localhost:8004/'

HEIGHT_RELESE_NOTE_ACTIVE = 1
HEIGHT_CONTRIBUTOR_ACTIVE = 1
HEIGHT_COMMIT_WEEK_ACTIVE = 3
HEIGHT_PR_QUALITY_1 = 2
HEIGHT_ACT_MET_1 = 3

HEIGHT_CONTRIBUTORS_WELCO = 2
HEIGHT_CONTRIBUTION_GUIDE_WELCO = 3
HEIGHT_HELP_WANTED_WELCO = 3
HEIGHT_GOOD_FIRST_ISSUE_WELCO = 3
HEIGHT_PR_TEMPLATE_WELCO = 2
HEIGHT_DESCRIPTION_WELCO = 1
HEIGHT_CODE_OF_CONDUCT_WELCO = 3
HEIGHT_README_WELCO = 3
HEIGHT_ISSUE_TEMPLATE_WELCO = 2
HEIGHT_LICENSE_WELCO = 1
HEIGHT_ACT_MET_2 = 2
HEIGHT_PR_QUALITY = 3

METRIC_CONTRIBUTOR = 0.25
METRIC_COMMIT = 0.1
HEIGHT_ISSUE_ACTIVE_SUPPORT_QUESTION_2 = 2
HEIGHT_README_SUPPORT = 3
HEIGHT_ISSUE_TEMPLATE_SUPPORT = 2
HEIGHT_LICENSE_SUPPORT = 3
HEIGHT_DESCRIPTION_SUPPORT = 1
HEIGHT_CODE_OF_CONDUCT_SUPPORT = 1
HEIGHT_RELEASE_NOTE_SUPPORT = 3
HEIGHT_ISSUE_ACTIVE_SUPPORT = 3

ISSUE_METRIC_ONE = 0.5
ISSUE_METRIC_TWO = 4

WELCOMING_METRIC_QUESTION = 28
ACTIVE_METRIC_QUESTION = 10
SUPPORT_METRIC = 16
