URL_COMMIT = 'http://localhost:8001/'
URL_COMMUNITY = 'http://localhost:8002/'
URL_ISSUES = 'http://localhost:8003/'
URL_PR = 'http://localhost:8004/'

HEIGHT_CONTRIBUTORS_WELCO = 2
HEIGHT_CONTRIBUTION_GUIDE_WELCO = 3
HEIGHT_HELP_WANTED_WELCO = 3
HEIGHT_GOOD_FIRST_ISSUE_WELCO = 3
HEIGHT_PR_TEMPLATE_WELCO = 2
HEIGHT_DESCRIPTION_WELCO = 1
HEIGHT_CODE_OF_CONDUCT_WELCO = 3
HEIGHT_README_WELCO = 3
HEIGHT_ISSUE_TEMPLATE_WELCO = 2
HEIGHT_LICENSE_WELCO = 1
METRIC_CONTRIBUTOR = 0.25
HEIGHT_ISSUE_ACTIVE_SUPPORT_QUESTION_2 = 2
WELCOMING_METRIC_QUESTION = 28
HEIGHT_PR_QUALITY = 3
HEIGHT_README_SUPPORT = 3
HEIGHT_ISSUE_TEMPLATE_SUPPORT = 2
HEIGHT_LICENSE_SUPPORT = 3
HEIGHT_DESCRIPTION_SUPPORT = 1
HEIGHT_CODE_OF_CONDUCT_SUPPORT = 1
HEIGHT_RELEASE_NOTE_SUPPORT = 3
HEIGHT_ISSUE_ACTIVE_SUPPORT = 3
ISSUE_METRIC_ONE = 0.5
ISSUE_METRIC_TWO = 4
SUPPORT_METRIC = 16


