# Generated by Django 2.2 on 2019-04-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeOfConduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('repo', models.CharField(max_length=200)),
                ('code_of_conduct', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(default=None)),
            ],
        ),
    ]
